tls:
  certificates:
    - certFile: "/etc/traefik/tls/tls.crt"
      keyFile: "/etc/traefik/tls/tls.key"
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/tls/tls.crt"
        keyFile: "/etc/traefik/tls/tls.key"

http:
  serversTransports:
    tls-self-signed-transport:
      rootCAs:
        - /etc/traefik/tls/ca.crt
      certificates:
        - certFile: /etc/traefik/tls/tls.crt
          keyFile: /etc/traefik/tls/tls.key

  routers:
    nginx:
      rule: "Host(`nginx.local`)" #Host(`localhost`) && PathPrefix(`/nginx`)
      service: nginx
      entryPoints:
        - websecure
        - web
      tls: {}

  services:
    nginx:
      loadBalancer:
        serversTransport: tls-self-signed-transport
        servers:
          - url: http://nginx:80