# Static configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

api:
  insecure: true

log:
  level: "DEBUG"

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/traefik-dynamic.yml
    watch: true
